# Generated by Django 5.1 on 2025-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_is_active_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Без названия', max_length=100, verbose_name='Название картинки'),
        ),
    ]
