version: "3.9"

services:
  # ----------- PostgreSQL ---------------------------------------------------
  db:
    image: postgres:16-alpine
    container_name: rapwsinews_db
    restart: unless-stopped
    env_file:               # берём переменные из .env
      - .env
    environment:
      POSTGRES_DB:       ${POSTGRES_DB:-rapwsinews}
      POSTGRES_USER:     ${POSTGRES_USER:-rapwsinews_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rapwsinews_pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"        # localhost:5432 → контейнер

  # ----------- Redis --------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  # ----------- Django‑приложение -------------------------------------------
  web:
    build: .
    container_name: rapwsinews_web
    restart: unless-stopped
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn rapwsinews_api.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./:/app               # для live‑кодинга; уберите на prod
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"           # localhost:8000 → контейнер

volumes:
  postgres-data:
  redis-data:
